import os, sys

Import('env')


# Common files.
CommonFiles = Split("jaricom.c jcomapi.c jutils.c jerror.c jmemmgr.c jmemnobs.c")

# Compression library files.
ComprFiles = Split("""jcapimin.c jcapistd.c jcarith.c jctrans.c jcparam.c jdatadst.c jcinit.c jcmaster.c
                      jcmarker.c jcmainct.c jcprepct.c jccoefct.c jccolor.c jcsample.c jchuff.c
                      jcdctmgr.c jfdctfst.c jfdctflt.c jfdctint.c""")

# Decompression library files.
DecomprFiles = Split("""jdapimin.c jdapistd.c jdarith.c jdtrans.c jdatasrc.c jdmaster.c jdinput.c jdmarker.c
                        jdhuff.c jdmainct.c jdcoefct.c jdpostct.c jddctmgr.c jidctfst.c
                        jidctflt.c jidctint.c jdsample.c jdcolor.c jquant1.c jquant2.c jdmerge.c""")


env_jpeg=env.Clone()

if sys.platform.startswith("linux"):
    # -Wno-main is required because libjpeg has local variables with name "main", which otherwise trigger "warning: main is usually a function".
    env_jpeg.Append(CCFLAGS=["-Wno-main"])

env_jpeg.StaticLibrary("cfs_jpeg", CommonFiles + ComprFiles + DecomprFiles)
