/*
Cafu Engine, http://www.cafu.de/
Copyright (c) Carsten Fuchs and other contributors.
This project is licensed under the terms of the MIT license.
*/

#include "WelcomePage.hpp"

#include "FontWizard.hpp"

#include "wx/wx.h"


WelcomePageT::WelcomePageT(FontWizardT* Parent)
    : wxWizardPageSimple(Parent)
{
    // Note: The following code was generated by wxFormBuilder and copied here manually because wxFormbuilder
    // doesn't support wxWizardPage as base class.

	wxBoxSizer* bSizer1;
	bSizer1 = new wxBoxSizer( wxVERTICAL );

	wxStaticText* m_staticText1;
	m_staticText1 = new wxStaticText( this, wxID_ANY, wxT("Welcome to the FontWizard!\n\nThis wizard will help you to convert fonts into the Cafu font format for use with the Cafu GUI system.\n\nTo start the wizard, please click on \"Next\"."), wxDefaultPosition, wxDefaultSize, 0 );
	m_staticText1->Wrap( -1 );
	bSizer1->Add( m_staticText1, 1, wxALL|wxEXPAND, 5 );

	this->SetSizer( bSizer1 );
	this->Layout();
}
