import os, sys

Import('env', 'buildMode')

gameEnv = env.Clone()

if sys.platform=="win32":
    gameEnv.Append(LIBS=Split("MatSys cfsLib ClipSys png cfs_jpeg z lua"))

gameEnv.SharedLibrary("VSWM", Glob("*.cpp")+Split("Libs/IntMatrix.cpp Libs/LookupTables.cpp"))
