import os, sys

Import('env', 'buildMode')

gameEnv = env.Clone()

gameEnv.Append(CPPDEFINES=[("GAME_NAME", "VSWM")]);

gameEnv.StaticLibrary("VSWM", Glob("*.cpp")+Split("Libs/IntMatrix.cpp Libs/LookupTables.cpp"))
