import os, sys

Import('env')


env.StaticLibrary("z", Split("adler32.c compress.c crc32.c deflate.c gzio.c inffast.c inflate.c infback.c inftrees.c trees.c uncompr.c zutil.c"))
env.StaticLibrary("minizip", Split("contrib/minizip/unzip.c contrib/minizip/ioapi.c"), CPPPATH=["."])
