import os, sys

Import('env', 'buildMode')

gameEnv = env.Clone()

gameEnv.Append(CPPPATH=['#/ExtLibs/bullet/src'])
gameEnv.Append(CPPPATH=['#/ExtLibs/lua/src'])

gameEnv.StaticLibrary("DeathMatch", Glob("*.cpp")+Split("Libs/LookupTables.cpp Libs/Physics.cpp"))
