import os, sys

Import('env')

# The NON-UNIX-USE file provides all the basic info for the details of this SConscript.
env_pcre = env.Clone()

env_pcre.Append(CPPDEFINES=["HAVE_CONFIG_H"])
env_pcre.Append(CPPPATH=["include", "."])   # As per step (6) from the NON-UNIX-USE file, make sure our local headers are found first.

# This is step (6) from the NON-UNIX-USE file, section "GENERIC INSTRUCTIONS FOR THE PCRE C LIBRARY".
env_pcre.StaticLibrary("pcre", Glob("pcre_*.c"))

# This is step (8) from the NON-UNIX-USE file, section "GENERIC INSTRUCTIONS FOR THE PCRE C LIBRARY".
# env_pcre.StaticLibrary("pcreposix", "pcreposix.c")

# This is step (9) from the NON-UNIX-USE file, section "GENERIC INSTRUCTIONS FOR THE PCRE C LIBRARY".
# env_pcre.Program("pcretest", "pcretest.c", LIBS=["pcre", "pcreposix"], LIBPATH=["."])

# This is the C++ wrapper library, used by the Collada-DOM.
env_pcre.StaticLibrary("pcrecpp", "pcrecpp.cc")
