import os, sys

Import('env')


env_vorbis=env.Clone()
env_vorbis.Append(CPPPATH=["include", "lib", "#/ExtLibs/libogg/include"])

if sys.platform.startswith("linux"):
    # These libraries will be linked to a .so, thus we have to compile with -fpic.
    env_vorbis.Append(CCFLAGS=["-fpic"])


env_vorbis.StaticLibrary("vorbis",
    Split("""lib/analysis.c lib/bitrate.c lib/block.c lib/codebook.c lib/envelope.c lib/floor0.c
             lib/floor1.c lib/info.c lib/lookup.c lib/lpc.c lib/lsp.c lib/mapping0.c lib/mdct.c
             lib/psy.c lib/registry.c lib/res0.c lib/sharedbook.c lib/smallft.c lib/synthesis.c
             lib/vorbisenc.c lib/window.c"""))

env_vorbis.StaticLibrary("vorbisfile", ["lib/vorbisfile.c"])
